<a href="https://colab.research.google.com/github/stepsbtw/Machine-Learning/blob/main/00_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Redes Neurais Artificiais
Em linhas gerais, uma RNA é uma coleção de funções aninhadas que são realizadas emcima de alguns dados de entrada.

Essas funções são definidas por parâmetros (pesos e viéses).

No Pytorch, são armazenados em **TENSORES**

# Pytorch : Conceitos Básicos

Tensor é um nome genérico para dentodar vários objetos matemáticos.

Um tensor vai ser qualquer array n-dimensional de números.

Um tensor tem apenas um único tipo de dados!

In [1]:
import torch

meu_tensor = torch.tensor(42.0)

print(meu_tensor) # um número é um tensor!
print(meu_tensor.dtype)

tensor(42.)
torch.float32


In [2]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6]])

tens = torch.tensor(arr)
print(tens)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [3]:
print(tens[-1])
print(tens[0])

tensor([5, 6])
tensor([1, 2])


In [4]:
tens[0][0] = 0.745
print(tens)

tensor([[0, 2],
        [3, 4],
        [5, 6]])


Como foi dito, um tensor tem apenas UM tipo de dados!

In [5]:
y = torch.tensor([
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ]
   ])

# TENSOR TRIDIMENSIONAL!
y

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

O tamanho de cada dimensão pode ser checado!

In [6]:
y.shape

torch.Size([3, 2, 3])

Lista com 3 Listas (com 2 Listas (com 3 elementos))

#Operações entre tensores

In [7]:
w = torch.tensor([0.3, 0.5])
x = torch.tensor([1.0, 2.0])
b = torch.tensor([0.5, 10.0])

y = w*x+b # PRODUTO DE HADAMAR

y

tensor([ 0.8000, 11.0000])

Note que * vai multiplicar elemento por elemento.

Porém temos a operação @ que **Multiplica TENSORES**

In [8]:
A = torch.tensor([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8],
                  [9, 7, 8],
                  [7, 6, 5]])

B = torch.tensor([[0, 1, 2, 3],
                  [3, 4, 5, 6],
                  [7, 8, 9, 10]])

C = A @ B
C
# D = B @ A impossivel

tensor([[ 17,  20,  23,  26],
        [ 47,  59,  71,  83],
        [ 77,  98, 119, 140],
        [ 77, 101, 125, 149],
        [ 53,  71,  89, 107]])

É basicamente uma multiplicação de matrizes ( só que podemos ter n dimensões )

- A : 5x3
- B : 3x4
- A @ B : 5x4

In [9]:
A = torch.tensor([[7, 6, 5]])

B = torch.tensor([[0, 1, 2, 3],
                  [3, 4, 5, 6],
                  [7, 8, 9, 10]])

C = A @ B
C

tensor([[ 53,  71,  89, 107]])

Além disso podemos **TRANSPOR** tensores

In [10]:
M = torch.tensor([[0, 1, 2, 3],
                  [3, 4, 5, 6],
                  [7, 8, 9, 10]])
M.t()

tensor([[ 0,  3,  7],
        [ 1,  4,  8],
        [ 2,  5,  9],
        [ 3,  6, 10]])

MATRIZ é um **TENSOR 2D**

### Algumas propriedades e funções dos TENSORES

**torch.empty**

Cria um tensor não inicializado com o formato especificado. (lixo de memória.)

In [12]:
import torch

tensor = torch.empty(2,3) # tensor 2x3

tensor2 = torch.empty(2,3,4, dtype=torch.float64)

# autograd records operations of the tensor
tensor3 = torch.empty(2,3, requires_grad=True)

OBS : requires_grad = True -> importante salvar as operacoes pra poder fazer o backpropagation depois.

**torch.full**

cria um tensor com determinado tamanho e preenche tudo com um valor específico.



In [13]:
tensor = torch.full((3,3), 7) # 3x3 com valor 7

**torch.cat**

a funcao cat concatena (junta) dois ou mais tensores ao longo de uma dimensao especifica.

útil para combinar tensores em uma única matriz ao longo de um eixo específico.

In [15]:
tensor1 = torch.tensor([[1,2], [3,4]])
tensor2 = torch.tensor([[5,6], [7,8]])

result = torch.cat((tensor1, tensor2), dim=1) # horizontal
result

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [16]:
torch.cat((tensor1,tensor2), dim=0) # vertical

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

**torch.reshape**

usada pra alterar a forma (ou dimensao) de um tensor sem alterar os seus dados subjacentes.

In [21]:
tensor_1d = torch.tensor([1,2,3,4,5,6])
print(tensor_1d)

# remodelando para 2D
tensor_2d = torch.reshape(tensor_1d, (2, 3)) # d1 = tam 2, d2 = tam 3 cada
print(tensor_2d)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [28]:
tensor = torch.reshape(tensor_2d, (1,-1))
tensor

tensor([[1, 2, 3, 4, 5, 6]])

In [35]:
tensor = torch.reshape(tensor, (3,2,-1)) # d1 = 3, d2 = 2, d3 = inferida (1)
tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [37]:
tensor = torch.reshape(tensor_2d, (2,3,-1))
tensor

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

**torch.randn**

gera tensores com elementos amostrados a partir de uma normal padrao, util por exemplo em inicializar RNAs.

In [40]:
tensor = torch.randn(2,4,5) # d1 = tam 2, d2 = tam4, d3 = tam5
tensor

tensor([[[-1.2646, -1.4318,  0.3280,  0.2555,  2.4488],
         [ 0.5989, -0.6183,  0.2397, -0.0943,  0.2298],
         [ 0.6209, -0.7417, -0.3219, -0.6226,  0.7816],
         [-1.4468,  1.3902,  1.9538,  0.4260, -0.3559]],

        [[-0.4463,  1.1527, -0.2223, -0.2305,  2.4942],
         [-1.6334,  1.2346, -0.6907,  0.6767, -0.9176],
         [ 0.3336, -1.0917, -0.4600, -0.1556,  0.1675],
         [ 0.3668,  0.4031, -0.2175, -0.0719,  1.0265]]])

**torch.sum**

soma ao longo de uma determinada dimensao

In [43]:
x = torch.tensor([[1,2,3],[4,5,6]])

total_sum = torch.sum(x) # SOMA TODOS ELEMENTOS

sum_dim0 = torch.sum(x, dim=0)
sum_dim1 = torch.sum(x, dim=1)

total_sum, sum_dim0, sum_dim1 # retorna tensores com esses valores!

(tensor(21), tensor([5, 7, 9]), tensor([ 6, 15]))

**torch.zero**

zera todos elementos

In [45]:
x.zero_()
x

tensor([[0, 0, 0],
        [0, 0, 0]])

**torch.from_numpy**

funcao usada pra converter array numpy em um tensor.
MAS qualquer alteracao feita no array vai alterar o tensor também (e vice-versa).

### **torch.backward**

Essencial no treinamento das redes neurais. Usada para calcular os gradientes dos parâmetros do modelo em relacao a uma função de custo. Depois usados pra atualizar os pesos do modelo.

(Gradient Descent / Backpropagation)

- Calcula os gradientes : loss.backward(), realiza a retropropagacao atraves do grafo construido durante a computacao da perda, calcula os gradientes da funcao custo em relacao a todos os parametros que possuem **REQUIRES_GRAD = True**

- Armazenamento dos Gradientes : Os gradientes calculados são armazenados nos atributos **.grad**, usados pelo otimizador pra ajustar os pesos durante o treinamento

In [53]:
x = torch.tensor(.3, )
w = torch.tensor(.4, requires_grad=True)
b = torch.tensor(.5, requires_grad=True)

y = w*x+b
y

tensor(0.6200, grad_fn=<AddBackward0>)

In [54]:
y.backward()

print("dy/dw = ", w.grad) # y em relacao a w = x
print("dy/dx = ", x.grad) # y em relacao a x, DEVERIA ser = w. MAS nao ativei o require_grad
print("dy/db = ", b.grad) # y em relacao a b = 1

dy/dw =  tensor(0.3000)
dy/dx =  None
dy/db =  tensor(1.)


**torch.no_grad()**

A função é um contexto gerenciador que desativa a computação do gradiente.

Durante a inferencia ou avaliacao do modelo, para economizar memoria e melhorar a eficiencia, vale a pena.

# Regressão Linear com Pytorch