<a href="https://colab.research.google.com/github/stepsbtw/Machine-Learning/blob/main/00_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Redes Neurais Artificiais
Em linhas gerais, uma RNA é uma coleção de funções aninhadas que são realizadas emcima de alguns dados de entrada.

Essas funções são definidas por parâmetros (pesos e viéses).

No Pytorch, são armazenados em **TENSORES**

# Pytorch : Conceitos Básicos

Tensor é um nome genérico para dentodar vários objetos matemáticos.

Um tensor vai ser qualquer array n-dimensional de números.

Um tensor tem apenas um único tipo de dados!

In [2]:
import torch

meu_tensor = torch.tensor(42.0)

print(meu_tensor) # um número é um tensor!
print(meu_tensor.dtype)

tensor(42.)
torch.float32


In [13]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6]])

tens = torch.tensor(arr)
print(tens)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [14]:
print(tens[-1])
print(tens[0])

tensor([5, 6])
tensor([1, 2])


In [17]:
tens[0][0] = 0.745
print(tens)

tensor([[0, 2],
        [3, 4],
        [5, 6]])


Como foi dito, um tensor tem apenas UM tipo de dados!

In [19]:
y = torch.tensor([
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ]
   ])

# TENSOR TRIDIMENSIONAL!
y

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

O tamanho de cada dimensão pode ser checado!

In [20]:
y.shape

torch.Size([3, 2, 3])

Lista com 3 Listas (com 2 Listas (com 3 elementos))

#Operações entre tensores

In [25]:
w = torch.tensor([0.3, 0.5])
x = torch.tensor([1.0, 2.0])
b = torch.tensor([0.5, 10.0])

y = w*x+b

y

tensor([ 0.8000, 11.0000])

Note que * vai multiplicar elemento por elemento.

Porém temos a operação @ que **Multiplica TENSORES**

In [32]:
A = torch.tensor([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8],
                  [9, 7, 8],
                  [7, 6, 5]])

B = torch.tensor([[0, 1, 2, 3],
                  [3, 4, 5, 6],
                  [7, 8, 9, 10]])

C = A @ B
C
# D = B @ A impossivel

tensor([[ 17,  20,  23,  26],
        [ 47,  59,  71,  83],
        [ 77,  98, 119, 140],
        [ 77, 101, 125, 149],
        [ 53,  71,  89, 107]])

É basicamente uma multiplicação de matrizes ( só que podemos ter n dimensões )

- A : 5x3
- B : 3x4
- A @ B : 5x4

In [31]:
A = torch.tensor([[7, 6, 5]])

B = torch.tensor([[0, 1, 2, 3],
                  [3, 4, 5, 6],
                  [7, 8, 9, 10]])

C = A @ B
C

tensor([[ 53,  71,  89, 107]])

Além disso podemos **TRANSPOR** tensores

In [29]:
M = torch.tensor([[0, 1, 2, 3],
                  [3, 4, 5, 6],
                  [7, 8, 9, 10]])
M.t()

tensor([[ 0,  3,  7],
        [ 1,  4,  8],
        [ 2,  5,  9],
        [ 3,  6, 10]])

MATRIZ é um **TENSOR 2D**